### ISSUE TITLE
Improve ImageSlider

### ISSUE THREAD

**Issue by yxqd** [scikit-beam/ipywe#13]
The zooming of the image display works well. The widget can be more useful with the following functionalities: 
* show x y coordinates and value
* add contrast selector

**Comment by ilumsden** [comment]
Wouldn't it just be easier to implement the new stuff from ImageDisplay in ImageSlider than to implement all the stuff from ImageSlider (except for the horizontal slider) in ImageDisplay?

**Comment by yxqd** [comment]
I guess you are right. If it is easier, maybe just add the zoom
functionality into the image slider. The image viewer would be just a
special case where there is only one image. Things to note

* Zoom should happen to all images
* The cursor coordinates should be the coordinates at the original image, not the zoomed image
* Add a display of the ROI information (left-top, left-bottom, right-top, right-bottom)

If you agree, I would change the title of this ticket to "improve imageslider".

**Comment by ilumsden** [comment]
Addressed in #14

**Comment by ilumsden** [comment]
**Closed by #14 and #17**
