### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by JeanBilheux** [scikit-beam/ipywe#18]
Should we add a requirement.txt file to this project in order to know what are all necessary libraries?

**Comment by yxqd** [comment]
You mean dependencies?

**Comment by yxqd** [comment]
See https://github.com/neutrons/ipywe/blob/3c22db6d336be6cc84a6120be1125b0bbdc9b01a/setup.py#L9

**Comment by JeanBilheux** [comment]
I noticed that scipy is necessary and because it also use the imresize method, pillow must be installed as well. I just added a requirements.txt file to the repo.

**Comment by yxqd** [comment]
Great. It would be nice to add those missing packages to setup.py. According to [this Stackoverflow thread](https://stackoverflow.com/questions/14399534/reference-requirements-txt-for-the-install-requires-kwarg-in-setuptools-setup-py) (scroll down to the answer  starting with "On the face of it, it does seem that requirements.txt and setup.py are silly duplicates"),  setup.py/install_requires and requirements.txt serve different purpose while both specify dependencies. 

In the long run, for the sake of easy installation by users, it would be better to create conda packages for ipywe and specify the dependencies in the conda specification file.

**Comment by JeanBilheux** [comment]
ok, so looks like I should add pillow to the setup.py file instead. requirements.txt will be more about listing all the dependencies (and dependencies of dependencies...etc) needed to get the library running.

**Comment by yxqd** [comment]
Replace this with #23
