### ISSUE TITLE
ImageSlider: minor improvements to side displays

### ISSUE THREAD

**Issue by yxqd** [scikit-beam/ipywe#22]
* ROI: left=?, right=?, ...
* Z range: also show the current z-range set by the contrast control

**Comment by ilumsden** [comment]
What exactly do you mean by this?

**Comment by ilumsden** [comment]
Commit 801bc89 has addressed these enhancements. However, it also broke the vertical slider. I'm working on of fix for this issue.

**Comment by ilumsden** [comment]
Commit 74d314f fixes the bug mentioned above. A pull request for these enhancements will be made at the same time as the pull request for #21.

**Comment by ilumsden** [comment]
Closed by #24.
