### ISSUE TITLE
Conda Install Not Working

### ISSUE THREAD

**Issue by ilumsden** [scikit-beam/ipywe#34]
@yxqd 
I just tried to see if the `conda install ipywe` command would work on my computer, and conda did not find it. Instead it raised the following error:

```
PackageNotFoundError: Package missing in current linux-64 channels: 
  - ipywe

Close matches found; did you mean one of these?

    ipywe: pywget

```

**Comment by yxqd** [comment]
It should be

     $ conda install -c neutrons ipywe

Sorry I forgot to mention the anaconda channel, "neutrons"
