### ISSUE TITLE
Version of Ipywe not Updating in Conda

### ISSUE THREAD

**Issue by ilumsden** [scikit-beam/ipywe#44]
I'm not sure if this is an issue or not, but I'll put it here just in case.

Currently, when you install ipywe through conda, it installs version 0.1.0. However, in the _version.py and package.json files, the version is 0.1.1a1. Also, the current conda installation does not contain several changes made to the ImageSlider and ImageDisplay widgets.

**Comment by yxqd** [comment]
Done. See 75c6945 and https://anaconda.org/neutrons/ipywe/files

**Comment by ilumsden** [comment]
Thanks @yxqd
