### ISSUE TITLE
Error when trying to import ipywe.imageslider

### ISSUE THREAD

**Issue by JeanBilheux** [scikit-beam/ipywe#48]
Using python 3.5, I get the following error when trying to import imageslider
```
>>> import ipywe.imageslider
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-9-0da379c41c9d> in <module>()
      1 import NeuNorm
----> 2 import ipywe.imageslider
      3 from __code.normalization import utilities, gui_widgets
      4 
      5 ipts = utilities.get_ipts()

/Users/j35/anaconda/envs/py35/lib/python3.5/site-packages/ipywe/imageslider.py in <module>()
      2 from . import base
      3 from IPython.display import display, HTML, clear_output
----> 4 from cStringIO import StringIO
      5 from traitlets import Unicode, Integer, Float, HasTraits, observe
      6 import sys, os

ImportError: No module named 'cStringIO'
```

**Comment by ilumsden** [comment]
@JeanBilheux, have you updated your copy of ipywe in a while? As of the merging of pull request #43, that import should be in an if-statement that prevents it from being imported if Python 3.X is being used. I just checked the code for imageslider in the master branch, and it has this if-statement.

**Comment by ilumsden** [comment]
I should also say that the reason it's raising an error is because the StringIO and cStringIO modules have been replaced with the io module as of Python 3.0.

**Comment by JeanBilheux** [comment]
I use > pip install but maybe it's an older version. I will use my local copy and see if it works. Thanks

**Comment by yxqd** [comment]
You should be able to use conda to install:

$ conda install -c neutrons ipywe
​

**Comment by ilumsden** [comment]
@yxqd, could the `pip install` command be "failing" because of something with versioning in the setup.py file? Just by looking at the commits to it vs the commits to the other versioning files, it doesn't appear that setup.py was updated for the newest version.

**Comment by JeanBilheux** [comment]
are we sure about the conda command? Package is missing according to conda !
```
$ conda install -c neutrons ipywe
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: .
Error: Package missing in current osx-64 channels:
  - ipywe

Close matches found; did you mean one of these?

    ipywe: pywget

You can search for packages on anaconda.org with

    anaconda search -t conda ipywe
```

**Comment by ilumsden** [comment]
Conda definitely works. I've installed it on several conda environments.

**Comment by ilumsden** [comment]
And, that includes the most recent update.

**Comment by ilumsden** [comment]
Version, not update.

**Comment by yxqd** [comment]
Jean: which python 3 version are you using?

**Comment by ilumsden** [comment]
I'm not sure why @JeanBilheux is having the problem he is, but I did find another one. I tried installing it through conda in a Python 3.6.2 environment, and the install failed because it said that there was still something preventing the package from working with Python 3.X.

**Comment by JeanBilheux** [comment]
I'm using Python 3.6.1

**Comment by yxqd** [comment]
I just uploaded the py3.6 package to anaconda. Please give it a try

**Comment by ilumsden** [comment]
It works.

**Comment by yxqd** [comment]
@JeanBilheux is this working for you now?
