### ISSUE TITLE
add image slider

### ISSUE THREAD

**Issue by yxqd** [scikit-beam/ipywe#5]
A widget that allows viewing an image series with cursor coordinates and value outputs and contrast adjustment.

**Comment by yxqd** [comment]
@ilumsden, could you please fix the following:

At https://github.com/neutrons/ipywe/blob/54279e0d093c5f259f9860b829fc998053e43765/ipywe/imageslider.js#L143 , change "children" to "find"

At
https://github.com/neutrons/ipywe/blob/54279e0d093c5f259f9860b829fc998053e43765/ipywe/imageslider.js#L47 and https://github.com/neutrons/ipywe/blob/54279e0d093c5f259f9860b829fc998053e43765/ipywe/imageslider.js#L87 don't set "id". Please use addClass if necessary and update related code.

**Comment by yxqd** [comment]
@ilumsden : can we remove "\n\n" at https://github.com/neutrons/ipywe/blob/54279e0d093c5f259f9860b829fc998053e43765/ipywe/imageslider.js#L88?

**Comment by ilumsden** [comment]
I found a problem with using the set_css function. Apparently, if this function is used and you have multiple ImageSlider widgets open in the same notebook, any changes to width or height that you make for one widget will affect the other. I'm working on transferring this function's functionality into the imageslider.js.

**Comment by yxqd** [comment]
Sounds great!

**Comment by yxqd** [comment]
This was resolved by #9
