### ISSUE TITLE
fileselector crashing when reaching home folder on analysis computer

### ISSUE THREAD

**Issue by JeanBilheux** [scikit-beam/ipywe#50]
Using **fileselector.FileSelectorPanel** on analysis computer (cg1d-analysis2...), tool crash when reaching home folder. Error message is 

```
FileNotFoundError: [Errno 2] No such file or directory: '/SNS/users/j35/thindrives'
```

**Comment by ilumsden** [comment]
What version of ipywe are you using? I thought the most recent version
contained code to prevent that error.

**Comment by ilumsden** [comment]
Actually, I'm not sure why that error's appearing in the first place.
Assuming j35 is your home directory, there should be no reason that
errorr's appearing, unless "thindrives" is a broken symlink.

**Comment by JeanBilheux** [comment]
I'm using a local copy so you are right, my version is out of date. I removed the folder (broken link) and no more error...so it's fixed. Thanks.
