### ISSUE TITLE
Manual input of path

### ISSUE THREAD

**Issue by JeanBilheux** [scikit-beam/ipywe#51]
The fileselector within the notebook is a awesome feature but sometimes we have to go through a lot of folders before reaching our final folder, it would be nice if there was on top of the widgets, a text box that allow us to enter the path manually.

**Comment by ilumsden** [comment]
This might just be a workaround, but you can specify the starting directory
in the widget's constructor.

**Comment by JeanBilheux** [comment]
That's correct and this is a great feature. But sometimes they retrieve the data for example on one side of the tree and they want to save another set of files 5 or 6 folders above it.

**Comment by yxqd** [comment]
I agree this would be a nice new feature. Need a bit of thought how to implement this.

**Comment by yxqd** [comment]
Add a text field to show the current directory, and it also allows a user to input the new directory
