### ISSUE TITLE
ImageSlider does not load successfully when running on Python 3

### ISSUE THREAD

**Issue by ilumsden** [scikit-beam/ipywe#55]
When I try to run the ImageSlider widget on Python 3 (3.6) I get the following series of errors in the web console:
```
> Wrong widget protocol version: received protocol version '', but was expecting major version '2'
> Couldn't process kernel message Wrong widget protocol version: received protocol version '', but was expecting major version '2'
```
Also, beneath the code cell (where the widget would normally appear, I got the following:
```
Widget Javascript not detected. It may not be installed or enabled properly.
Error rendering Jupyter widget. Widget not found:
{"model_id":"b030ed1215ff467dbba5de6cb5b299f"}
```

**Comment by yxqd** [comment]
Are you trying a conda release, or the code in development? If the latter, which branch?

**Comment by ilumsden** [comment]
The code in development. I'm on your 53-imprv-imgslider branch.

**Comment by yxqd** [comment]
Refs #53

**Comment by yxqd** [comment]
I just tried it on my machine, it works fine. The error message you saw may be solved by reloading the page (so that the javascript libraries will be reloaded). Could you give that a try?

**Comment by ilumsden** [comment]
I just tried, and it still didn't work. I'm not sure why its acting up like this. Essentially, all I do is run the dev_js_update.sh file (to confirm Javascript extensions and run setup.py) and launch the Jupyter Notebook.

**Comment by ilumsden** [comment]
Now that I think about it, what kernel did you run? I'm running on a generic Python 3 kernel.

**Comment by yxqd** [comment]
Here is how I tested it

0. deactivate from previous conda environment, if necessary
1. create a new conda environment with python 3 and activate
`conda create -n test-ipywe-py3 python=3.6`
`source activate test-ipywe-py3`
2. install ipywe dependencies
`conda install ...`
3. install ipywe dev version
`cd /path/to/ipywe; ./dev_js_update.sh`
4. start jupyter server and test
`jupyter notebook`

**Comment by ilumsden** [comment]
Yeah, that's what I did too. It's really weird that it's not working. You said that you tried it, and it worked, right?

**Comment by ilumsden** [comment]
The problem appeared to have been with ipywidgets. Apparently, ipywidgets 6.0 is not compatible with widgetsnbextension 3.0. Based on jupyter-widgets/ipywidgets#1698, this seems to be an issue with ipywidgets. Supposedly, this should be resolved with ipywidgets 7.0. Until that version is fully released (which might be already), I'd recommend that we try to limit the version of widgetsnbextension to less than 3.0. This should be fine because, from what I can tell, all versions of widgetsnbextension explicitly require either Python 2.7 or a version of Python greater than 3.3.

**Comment by ilumsden** [comment]
Ipywidgets 7.0 does fix this issue. I would recommend either using widgetsnbextension 2.0.1 (the main version before 3.0) or ipywidgets 7.0 (currently live on conda-forge) when running the widgets in Python 3.

**Comment by yxqd** [comment]
This is a problem with ipywidgets and widgetsnbextension, not ipywe itself. Added a note in README.md
