### ISSUE TITLE
New blank line everytime a folder is entered

### ISSUE THREAD

**Issue by JeanBilheux** [scikit-beam/ipywe#59]
A new blank line gets inserted at the top of the panel every time a folder is entered. After entering a few folder, user always needs to scroll down to see the entire panel.

**Comment by yxqd** [comment]
@JeanBilheux could you verify this fix works for you? You will need to install ipywe from source. Please see [Dev.md](https://github.com/scikit-beam/ipywe/blob/master/Dev.md#dev-installation)

**Comment by JeanBilheux** [comment]
Works great. Thanks.
