### ISSUE TITLE
Search tool does not clear itself

### ISSUE THREAD

**Issue by JeanBilheux** [scikit-beam/ipywe#78]
When user enter a search string and hit enter, the search works but the search string is still there. Any other folder selection will keep the search criteria...even if it looks like the string has been cleaned up.
![search_bug](https://user-images.githubusercontent.com/1138324/39636936-a4c69284-4f8f-11e8-9f06-92ae9db1880d.gif)

**Comment by yxqd** [comment]
@JeanBilheux should this be fixed by #79?

**Comment by JeanBilheux** [comment]
that's correct.
